export const ORGANIZER_LOGIN_REQUEST = "ORGANIZER_LOGIN_REQUEST";
export const ORGANIZER_LOGIN_SUCCESS = "ORGANIZER_LOGIN_SUCCESS";
export const ORGANIZER_LOGIN_FAIL = "ORGANIZER_LOGIN_FAIL";
export const ORGANIZER_LOGOUT = "ORGANIZER_LOGOUT";

export const ORGANIZER_REGISTER_REQUEST = "ORGANIZER_REGISTER_REQUEST";
export const ORGANIZER_REGISTER_SUCCESS = "ORGANIZER_REGISTER_SUCCESS";
export const ORGANIZER_REGISTER_FAIL = "ORGANIZER_REGISTER_FAIL";
export const ORGANIZER_REGISTER_MESSAGE = "ORGANIZER_REGISTER_MESSAGE";
